// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCustomIgnoreRules():Promise<string>;

export function ListFiles(arg1:string):Promise<Array<main.FileNode>>;

export function RequestShotgunContextGeneration(arg1:string,arg2:Array<string>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetCustomIgnoreRules(arg1:string):Promise<void>;

export function StartFileWatcher(arg1:string):Promise<void>;

export function StopFileWatcher():Promise<void>;
