// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateShotgunOutput(arg1:string,arg2:Array<string>):Promise<string>;

export function ListFiles(arg1:string):Promise<Array<main.FileNode>>;

export function SelectDirectory():Promise<string>;
